### ISSUE TITLE
Getting "Has no TestFixtures" message executing via nunit3-console.exe

### ISSUE THREAD

**Issue by agray** [nunit/nunit#1118]
The class which contains my [Test]s inherits from a class ("MyBase") which has a [TestFixtureSource]. MyBase in turn inherits from a class ("MyRoot") that contains my [TestFixture].

This was working beautifully and correctly under release 3.0.

nunit3-console is returning:

    1) Invalid : ...Tester.dll
    Has no TestFixtures

    Run Settings
        WorkDirectory: C:\Jenkins\workspace\Tester
        NumberOfTestWorkers: 8

    Test Run Summary
        Overall result: Failed
        Tests run: 0, Passed: 0, Errors: 0, Failures: 0, Inconclusive: 0
        Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
          Start time: 2015-12-06 06:46:52Z
          End time: 2015-12-06 06:46:52Z
          Duration: 0.072 seconds

**Comment by CharliePoole** [comment]
Can you provide us with a test case?

**Comment by agray** [comment]
Please have a look at this [this](https://github.com/Full360Solutions/Saucery/blob/master/Saucery3/GuineaPigTests.cs)

SauceryBase has a [TestFixtureSource(typeof(SomeClass)] attribute. SauceryBase inherits from another class that has a [TestFixture] attribute.

SomeClass inherits from IEnumerable with a public IEnumerator GetEnumerator() method.

**Comment by agray** [comment]
This functionality was working correctly in Release 3.0.  This bug has been introduced in Release 3.0.1.  It is critical for me as my product relies on this working.

**Comment by CharliePoole** [comment]
I just filed two bugs against another open source project regarding problems that impact NUnit. In order to produce workable bugs and get some priority, I spent an hour putting together a simplified test case that stood on it's own and showed the project maintainers what was expected versus what was actually happening. They responded very rapidly.

Can you provide us with a simplified test case that stands on it's own - one we can compile - that shows the problem you are seeing? Without it, someone else will have to be interested enough to take on the bug, create the case, have you confirm that it's correct and then figure out how to fix it. 

Which do you think might be quicker? :-)

Charlie

**Comment by agray** [comment]
#715 is the issue that talks about the functionality that was kindly implemented but has become broken in release 3.0.1.  I will check all the commits between Release 3.0.0 and 3.0.1 to see if I can help narrow down where the bug has been introduced.

**Comment by CharliePoole** [comment]
That will work too. I still don't know what exactly you are reporting as broken, but if you find the cause it will probably become clear. :-)

As for the functionality of #715, it's still there. We use it. Our tests test it. What's we don't know is exactly what use case is now breaking for you. Whatever it is, that use case is not in our tests, so the fact that it worked before is basically some sort of happy accident.

If you are able to create a test case, we will include it to prevent future regressions.

**Comment by agray** [comment]
MyBase:
    [TestFixtureSource(typeof(ClassThatInheritsFromIEnumerable))]
    public class MyBase : MyRoot {
        protected RemoteWebDriver Driver;

        public MyBase(ClassReturnedByClassThatInheritsFromIEnumerable a) : base(a) {
        }

        [TearDown]
        public void Cleanup() {
            ...
            }
        }


MyRoot:
    [TestFixture]
    public abstract class MyRoot {
        protected string TestName;
        protected readonly SaucePlatform Platform;
        protected static SauceLabsStatusNotifier SauceLabsStatusNotifier;
        internal static SauceLabsFlowController SauceLabsFlowController;
        protected static SauceLabsAppiumRecommender SauceLabsAppiumRecommender;

        protected SauceryRoot(SaucePlatform platform) {
            Platform = platform;
        }

        static MyRoot() {
             ...
            }
        }

        [SetUp]
        public void Setup() {
            ...
        }

**Comment by CharliePoole** [comment]
Huh... the three dots don't compile.

Just kidding, we can try a do-nothing class with that structure and see what happens.

**Comment by agray** [comment]
The use case is simply that if ClassThatInheritsFromIEnumerable returns 10 instances of ClassReturnedByClassThatInheritsFromIEnumerable then 10 * 2 = 20 tests are executed.

Have just downgraded back to NUnit Release 3.0.0 and it is working...thus proving that this usecase has been broken in release 3.0.1.

**Comment by CharliePoole** [comment]
So what it is actually doing is not finding any tests, right?

The message about not finding any test fixtures could probably be worded better for this situation.  It usually means that there were no classes with test cases. There may actually be 10 empty test fixtures getting generated. Would you take a look at your XML output to see if that's the case?

**Comment by agray** [comment]
It certainly appears that it is not finding any tests.  It generates this message almost immediately and exits out.  No tests are executed.  Will have a look later tonight at the XML output and report back.

**Comment by agray** [comment]
Nothing in my XML output.  Tests fail immediately.

**Comment by CharliePoole** [comment]
Here is a minimal test I created to attempt to reproduce the bug.

```C#
    [TestFixture]
    public abstract class Issue1118_Root
    {
        protected readonly string Browser;

        protected Issue1118_Root(string browser)
        {
            Browser = browser;
        }

        [SetUp]
        public void Setup()
        {
        }
    }

    [TestFixtureSource(typeof(Issue1118_SourceData))]
    public class Issue1118_Base : Issue1118_Root
    {
        public Issue1118_Base(string browser) : base(browser)
        {
        }

        [TearDown]
        public void Cleanup()
        {
        }
    }

    public class Issue1118_Fixture : Issue1118_Base
    {
        public Issue1118_Fixture(string browser) : base(browser)
        {
        }

        [Test]
        public void DoSomethingOnAWebPageWithSelenium()
        {
        }

        [Test]
        public void DoSomethingElseOnAWebPageWithSelenium()
        {
        }
    }

    public class Issue1118_SourceData : IEnumerable
    {
        public IEnumerator GetEnumerator()
        {
            yield return "Firefox";
            yield return "Chrome";
            yield return "Internet Explorer";
        }
    }
```

The result has six test cases as expected.

If you can enhance it to the point of failure, we can take it from there.

**Comment by agray** [comment]
Investigating point of failure. It is broken when I upgrade back to release 3.0.1...investigating where exactly by comparing above example with mine

**Comment by agray** [comment]
Hmmm,  Well that was a bit screwed.  I've spent all night rebuilding my project from the ground up comparing my version with your example. Gradually add more and more of my original code base to the working example expecting to find the smoking gun....didn't find it.  My new code base is working with NUnit 3.0.1.

Don't know what is wrong with the old version of my codebase.  That's frustrating.

May I request that unit tests are captured and included in the bank of unit tests for this usecase.

I wouldn't want to debug that again!

Thanks

**Comment by CharliePoole** [comment]
I have a branch that contains the test I sent you, which I can merge. If you have others, I'll add them.

**Comment by agray** [comment]
I've been taking a dog fooding system test approach to date.  Less than ideal, I know.  I would love to offer you a bank of unit tests of this use case but i don't have any.

**Comment by CharliePoole** [comment]
No problem. Thought I'd ask anyway.

**Comment by CharliePoole** [comment]
I'm going to close this after adding the test to our codebase.

**Comment by agray** [comment]
Thank you.  That's fine.

**Comment by agray** [comment]
@CharliePoole where is the branch containing the unit tests you referred to?  I'd like to take look at them.

**Comment by CharliePoole** [comment]
@agray Thanks for the reminder. I pushed it and created a PR. Please take a look at
   https://github.com/nunit/nunit/pull/1157

**Comment by peppy** [comment]
I can still reproduce this on 3.7.1 by having a referenced framework that contains an abstract base class with either `[TestFixture]` or `[Test]` attributed attached to them, but no non-abstract tests.

Example: https://github.com/ppy/osu-framework/tree/7505b631b2627ee130a3ba3a8c360821e6b52122

**Comment by CharliePoole** [comment]
As far as NUnit is concerned, an abstract class by itself has no tests. It's only when you inherit from the class that tests actually exist.

You mention that this is a framework. Do the actual test classes ever refer to NUnit directly? If they don't - that is, if you are trying to hide NUnit behind the framework - then it will not currently work. You must have at least one reference to NUnit in the test assembly in order for the test to be loaded. We are working on alternate solutions for this.

**Comment by peppy** [comment]
Thanks for the response.

Basically we have a `Framework.Testing` project which contains an abstract representation of a `TestCase` as follows:

```
namespace osu.Framework.Testing
{
    public abstract class TestCase : Container
    {
        public virtual string Description => @"The base class for a test case";

        public readonly FillFlowContainer<StepButton> StepsContainer;
        private readonly Container content;

        protected override Container<Drawable> Content => content;

        [Test]
        public void RunTest()
        {
            using (var host = new HeadlessGameHost())
                host.Run(new TestCaseTestRunner(this));
        }

        ....
}
```

`TestCase`s which derive from this need not know how they are run by NUnit as a result. Unfortunately when the test runner runs it also inspects the `Framework.Testing` project which contains currently only this abstract representation.

I've fixed it by [adding a placeholder test](https://github.com/ppy/osu-framework/pull/934/commits/b72217a19f649b29a589ba6ea10c95f4cdd0cdcf), just thought I'd bring this up to make the issue known.

**Comment by CharliePoole** [comment]
Ah, I misunderstood and thought the problem was with the actual tests that derive from your abstract class.

In your case, you can just add the nunit NonTestAssembly attribute to the framework and it should be ignored. 

I'm on my phone, so don't trust my spelling of the attribute from memory.

**Comment by peppy** [comment]
That sounds like a great solution, but unfortunately it still seems to fail with the same error:

https://github.com/ppy/osu-framework/pull/934/commits/8e22db6f5184485408e32609b701873050c1913e
https://ci.appveyor.com/project/peppy/osu-framework/build/3553

**Comment by CharliePoole** [comment]
You are running nunit3-console 3.6.1

**Comment by ChrisMaddock** [comment]
I think NonTestAssemblyAttribute requires the `--skipNonTestAssemblies` flag to also be passed on the console.

@peppy - I took a quick look at your project - looks like you're currently letting AppVeyor auto-discover the test assemblies? I'd just specify the actual assembly in your appveyor.yml file.

**Comment by huronbikes** [comment]
So I'm getting the same thing when tests; I have an assembly that consists of three classes, all marked with a CategoryAttribute of Integration and an abstract base class that contains the one-time setup / teardown methods.
 
The problem only came up when updating the assembly's nunit dependency from 2.6.4 to 3.8.1, though I would imagine any 3.x nunit would trigger the issue.

& "c:\program files (x86)\nunit.org\nunit-console\nunit3-console.exe" `
	path-to-my-assembly `
	--where="cat !~ Integration && cat !~ Functional && class !~ Integration" `
	--noheader `
	--labels=All `
	--domain=Single `
	--process=Multiple `
	--agents=4 `
	--skipnontestassemblies `
	--result:"c:\temp\Test_Output.xml;format=nunit2"

**Comment by CharliePoole** [comment]
@huronbikes I'd question whether this is the "same thing". It looks to me as if you are simply filtering out all your test classes with the `--where` clause. You indicated that all your fixtures have the Integration category and the where rules them all out.

BTW, your command-line is a bit odd in several ways...

* You specify --domain=single meaning all assemblies run in the same domain together, but you only have one assembly.
* You specify --process=Multiple but again you only have one assembly.
* You specify --agents=4 to limit the number of separate processes to four, but .... same thing again. 😄 
* You specify --skipnontestassemblies, but there is only one assembly. Why would you specify the name of a non-test assembly in the first place?

**Comment by huronbikes** [comment]
Sorry, what's not clear is normally the nunit-console run is done against
an entire solution with those filters; there's about 19k unit tests after
filtering there across 50 or so test assemblies and fails against the
assembly I describe. I can replicate the failure with just the one
assembly. For now, I've worked around this by adding a TestFixtureAttribute
and a CatagoryAttribute to the base class.

I'll try throwing together a whole POC, that should clarify things.

On Aug 29, 2017 2:45 PM, "CharliePoole" <notifications@github.com> wrote:

@huronbikes <https://github.com/huronbikes> I'd question whether this is
the "same thing". It looks to me as if you are simply filtering out all
your test classes with the --where clause. You indicated that all your
fixtures have the Integration category and the where rules them all out.

BTW, your command-line is a bit odd in several ways...

   - You specify --domain=single meaning all assemblies run in the same
   domain together, but you only have one assembly.
   - You specify --process=Multiple but again you only have one assembly.
   - You specify --agents=4 to limit the number of separate processes to
   four, but .... same thing again. 😄
   - You specify --skipnontestassemblies, but there is only one assembly.
   Why would you specify the name of a non-test assembly in the first place?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nunit/nunit/issues/1118#issuecomment-325778443>, or mute
the thread

**Comment by CharliePoole** [comment]
I see, so the assembly with only integration tests is one of many. You would like it to be silently ignored. Is that it? 

The feature of implemented by `--skipnontestassemblies` is intended - obviously - to skip non-test assemblies. Your assembly is actually a test assembly, but no fixtures are selected as a result of the filter. In the past, we have dealt with this by silently ignoring such an assembly, so long as __some__ assembly in the list satisfied the filter condition. That facilitates running a filter across many assemblies. Apparently, we are no longer doing that.

The original fixture here had to do with inheriting a test fixture from a base class. It doesn't sound like you are having the same problem. It does look like a bug though. @rprouse How do you want to handle this - as a new issue?

**Comment by rprouse** [comment]
@huronbikes please open a new issue when you come up with a minimal reproduction. It would be easiest to track this in a clean issue that begins with a concrete example. It would also be helpful if you could factor it down to the minimum console command line to reproduce. Thanks.

**Comment by vrushb** [comment]
I am having issues running my specflow dll through nunit3 .I tried with nunit2.6.4 and it does not show errors but does not execute actual test .Spent 3 days but no clue
C:%Program Files (x86)%\Microsoft Visual Studio\2017\Professional\Common7\IDE
nunit3-console.exe \FIlePath\FileName.dll
Getting this error

```
1) Invalid : \FIlePath\FileName.dll
No suitable tests found in \FIlePath\FileName.dll
Either assembly contains no tests or proper test driver has not been found.
```

Is there any way to run specflow scenarios with nunit or MStest.exe

**Comment by rprouse** [comment]
@vrushb this issue was closed a couple of years ago. How are you installing NUnit? It looks to me like your assembly contains no NUnit tests. It could be because of a problem with how you are using SpecFlow. None of us use SpecFlow however, so you might want to ask for help from them. If you can reproduce the problem without SpecFlow installed, create a new issue here and we will help you.

**Comment by vrushb** [comment]
I tried installing from outside as well to run with older version.
Finally I could run the test through vstest.exe .So I am good .
Thanks for the suggestions. I will try.


Vrushali

**Comment by jnm2** [comment]
<sup>[edited to remove email reply artifacts that GitHub missed]<sup>
