### ISSUE TITLE
[Parallelizable] hangs after a few tests

### ISSUE THREAD

**Issue by AqlaSolutions** [nunit/nunit#2438]
This test runs 8 cases and then hangs (but still using my cpu). I'm using the latest R# with the latest nunit console runner available at this time.

    [TestFixture]
    public class NunitParallelizationTest
    {
        [Parallelizable(ParallelScope.All)]
        [Test]
        public void Test([Range(1, 10)] int x)
        {

        }
    }

Stack trace: https://www.screencast.com/t/k2hZPk95QBN

**Comment by CharliePoole** [comment]
Is the test literally empty of code, or are you just not showing it.

You can't use R# "with" the console runner, it's either one or the other. It looks like you are using R#, so please give it a try with the console runner.

**Comment by AqlaSolutions** [comment]
It's an empty test, right.
Ok, checking console runner.

**Comment by AqlaSolutions** [comment]
Checked, NUnit Console Runner 3.7.0 hangs too.

**Comment by CharliePoole** [comment]
OK thanks for clarifying. Somebody will take a look.

RE R#, we only have vague info on how they call us, so using the console to check is out best course.

**Comment by Singh400** [comment]
Hi, 

I can confirm I get the same hanging behaviour as described by @AqlaSolutions . `nunit-agent-x86.exe` just sits there chewing up my CPU doing nothing.

Cheers,
Indy

**Comment by ChrisMaddock** [comment]
I had a look into this, as it was getting in the way of solving https://github.com/nunit/nunit/issues/2428. I think I know what's going on, but I'm struggling a little understanding things. @CharliePoole - does the below seem sensible to you?

Based on:
- In the test above - the fixture is Non-Parallel (NP), all tests are parallel. 
- In this case, each test is assigned to a parallel-shift.
- The parallel shifts all run to end, and trigger OnEndOfShift [here](https://github.com/nunit/nunit/blob/7aeed1fbc74463285b302f6d79366dbea9ff7b50/src/NUnitFramework/framework/Internal/Execution/ParallelWorkItemDispatcher.cs#L249).
- One of these shifts then dispatches the OneTimeTearDown for the fixture to the NP queue, which is responsible for marking the Fixture `WorkItemState.Complete`, and allowing the other workers to shut down (i.e. break out of the OnEndOfShift loop)

The issue, I think, is that OnEndOfShift will call `RestoreQueues()` if there are any levels of isolation, without first checking that all work on all queues has been completed. I _think_ what is happening, is that the fixtures OneTimeTearDown is being dispatched to an NP queue, but then being lost, as RestoreQueues is being called for the end of another Shift. Adding the below seems to allow the shift to run to completion.

**OnEndOfShift() Before**
```
            if (_isolationLevel > 0)
                RestoreQueues();
```

**OnEndOfShift() After**
```
            if (_isolationLevel > 0 && Shifts.All(q => !q.HasWork))
                RestoreQueues();
```

Does this seem sensible? I'm a little mind-blown by queues and shifts right now, I'll be honest. 😆 I'm out of time for today, so thought I'd post for feedback before continuing - but does the above sound sensible?

**Comment by ChrisMaddock** [comment]
I'm afraid this is also in hotfix territory, if my analysis is right. cc @rprouse

**Comment by rprouse** [comment]
>I'm afraid this is also in hotfix territory, if my analysis is right.

Agreed, assigning to the milestone. I haven't looked at the code, but your analysis looks good. If I get a chance, I will review too. I am going to assign myself to this issue for tracking.

**Comment by ChrisMaddock** [comment]
@rprouse - I added some additional things to the milestone which I think would also belong in a hotfix - feel free to remove any if you disagree. 🙂

**Comment by CharliePoole** [comment]
@ChrisMaddock I finally got around to commenting on the PR. As indicated I'm concerned there is still a race condition similar to the one that we already fixed for terminating the app. I think something similar has to be done for terminating and removing a set of queues.

Because the Save/Restore was added on after the initial implementation, it's not well modeled in the object design. We may want to do a re-design at some point.

**Comment by ChrisMaddock** [comment]
I'm going to have to take my name off this issue for now - as finding a few spare hours to look at it over the next couple of weeks is proving difficult. Will revisit it in the interim if I can - but anyone is welcome to continue building on https://github.com/nunit/nunit/pull/2445

**Comment by ejones91** [comment]
I'm having this same problem, but only when using a SetUpFixture as well. Both R# and the console runner are hanging.

**Comment by jairbubbles** [comment]
Hello, after upgrading NUnit from 3.5.0 to 3.8.1 I'm experiencing a hang when running from console runner and R#. I do not use [Parallelizable] in those tests. When you have a prerelease version with the fix I'd be pleased to test it.

**Comment by ChrisMaddock** [comment]
@jairbubbles - this should be fixed by #2461. Will you try the package from the master build below?

**Comment by jairbubbles** [comment]
Unfortunately it doesn't fix the issue 😢 
It works ok with  3.7.1 though.

**Comment by jairbubbles** [comment]
(And it's broken starting from 3.8.0)

**Comment by ChrisMaddock** [comment]
@jairbubbles In that case you may be seeing a separate issue that we haven't seen before. Can you debug to break out a minimal example you can share with us, and then open a new issue?

Some tips, assuming you're using nunit3-console.exe to run:
1. Try running with `--labels:before` which outputs each test name. Does your run always hang on a certain test?
2. Try `--log:Verbose` - which will show the order tests are being executed, and by which workers. Are there any major differences between NUnit 3.7 and NUnit 3.8? If you have no parallelisation, this should hopefully be easier to compare.

**Comment by jairbubbles** [comment]
I'll do my best => #2467

**Comment by rprouse** [comment]
Tested with 3.9.0-dev-04639 and this has been fixed with the recent batch of parallizable fixes.
